env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  no-undef:
    - "off"
  react/prop-types:
    # Enable prop-types validation for React components
    - "warn"
